version: '3.2'

services:

  signup-db:
    image: dockersamples/mta-dev-signup-db:v1
    networks:
      - app-net
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.platform.os == windows

  signup-app:
    image: dockersamples/mta-dev-signup-app:v4
    ports:
    - mode: host
      published: 8085
      target: 80
    networks:
      - app-net
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.platform.os == windows
    networks:
      app-net: null

  message-queue:
    image: nats:1.0.4-nanoserver
    networks:
      - app-net
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.platform.os == windows

  elasticsearch:
    image: dockersamples/elasticsearch:5.6.0-nanoserver
    networks:
      - app-net 
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.platform.os == windows

  kibana:
    image: dockersamples/kibana:5.6.0-windowsservercore
    ports:
    - mode: host
      published: 5601
      target: 5601
    networks:
      - app-net 
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.platform.os == windows

  signup-index-handler:
    image: dockersamples/mta-dev-signup-index-handler:v1
    networks:
      - app-net 
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.platform.os == windows
      replicas: 2

  signup-save-handler:
    image: dockersamples/mta-dev-signup-save-handler:v1
    networks:
      - app-net 
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.platform.os == windows
      replicas: 4

  signup-homepage:
    image: dockersamples/mta-dev-signup-homepage:v1
    networks:
      - app-net 
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.platform.os == windows

networks:
  app-net: 