apiVersion: v1
kind: Service
metadata:
  name: whoami-np
  labels:
    pswebinar: '21.10'
    app: whoami
spec:
  selector:
    app: whoami
  ports:
    - name: http
      port: 8010
      targetPort: 80
      nodePort: 30010
  type: NodePort