apiVersion: v1
kind: Service
metadata:
  name: nerd-dinner-web
spec:
  ports:
    - port: 8080
      targetPort: 80
      name: nerd-dinner-web
  selector:
    app: nerd-dinner-web
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nerd-dinner-web
spec:
  selector:
    matchLabels:
      app: nerd-dinner-web
  template:
    metadata:
      labels:
        app: nerd-dinner-web
    spec:
      containers:
      - image: dockeronwindows/ch03-nerd-dinner-web:2e              
        imagePullPolicy: Always
        name: nerd-dinner-web
        ports:
        - containerPort: 80
          name: nerd-dinner-web
        volumeMounts:
          - name: nerd-dinner-config
            mountPath: "/nerd-dinner/config"
            readOnly: true
      volumes:
      - name: nerd-dinner-config
        secret:
          secretName: nerd-dinner-config
      nodeSelector:
        beta.kubernetes.io/os: windows
